"""Add remaining tables for meetings, board, resolutions, compliance, notifications

Revision ID: 65321c29b09a
Revises: 6ce4767d2f5d
Create Date: 2025-11-06 23:03:32.539781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65321c29b09a'
down_revision = '6ce4767d2f5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('term_length', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EMERITUS', name='memberstatus'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_board_members_id'), 'board_members', ['id'], unique=False)
    op.create_table('compliance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('FILING', 'POLICY', 'TRAINING', 'MEETING', 'CERTIFICATION', 'INSURANCE', 'AUDIT', name='compliancecategory'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.Enum('NONE', 'ANNUAL', 'QUARTERLY', 'MONTHLY', 'BIANNUAL', name='recurrencetype'), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'DUE_SOON', 'OVERDUE', 'COMPLETED', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('responsible_party_id', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('reference_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alert_days_before', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_party_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_items_id'), 'compliance_items', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('MEETING_INVITE', 'MEETING_REMINDER', 'DOCUMENT_UPLOAD', 'DOCUMENT_SHARED', 'ACTION_ITEM_ASSIGNED', 'ACTION_ITEM_DUE', 'COMPLIANCE_ALERT', 'RESOLUTION_VOTE', 'MESSAGE', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('committee_type', sa.Enum('STANDING', 'AD_HOC', 'SPECIAL', name='committeetype'), nullable=False),
    sa.Column('chair_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('charter', sa.Text(), nullable=True),
    sa.Column('meeting_frequency', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chair_id'], ['board_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committees_id'), 'committees', ['id'], unique=False)
    op.create_table('compliance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compliance_item_id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('proof_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ),
    sa.ForeignKeyConstraint(['proof_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_history_id'), 'compliance_history', ['id'], unique=False)
    op.create_table('officer_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_member_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_member_id'], ['board_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officer_roles_id'), 'officer_roles', ['id'], unique=False)
    op.create_table('committee_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('board_member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CHAIR', 'VICE_CHAIR', 'MEMBER', 'SECRETARY', name='committeerole'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_member_id'], ['board_members.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_members_id'), 'committee_members', ['id'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_type', sa.Enum('REGULAR', 'SPECIAL', 'COMMITTEE', 'ANNUAL', name='meetingtype'), nullable=False),
    sa.Column('meeting_date', sa.DateTime(), nullable=True),
    sa.Column('meeting_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('virtual_link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meetingstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('minutes_document_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['minutes_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_table('agenda_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_allocated', sa.Integer(), nullable=True),
    sa.Column('presenter', sa.String(length=255), nullable=True),
    sa.Column('related_document_ids', sa.JSON(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_items_id'), 'agenda_items', ['id'], unique=False)
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('attendance_status', sa.Enum('INVITED', 'CONFIRMED', 'ATTENDED', 'ABSENT', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_attendees_id'), 'meeting_attendees', ['id'], unique=False)
    op.create_table('meeting_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_role', sa.Enum('PRE_READ', 'AGENDA', 'MINUTES', 'RESOLUTION', 'SUPPORTING', name='documentrole'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_documents_id'), 'meeting_documents', ['id'], unique=False)
    op.create_table('resolutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('resolution_type', sa.Enum('ORDINARY', 'SPECIAL', 'CONSENT', 'EMERGENCY', name='resolutiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROPOSED', 'PASSED', 'FAILED', 'TABLED', 'WITHDRAWN', name='resolutionstatus'), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('proposed_by_id', sa.Integer(), nullable=False),
    sa.Column('votes_aye', sa.Integer(), nullable=True),
    sa.Column('votes_nay', sa.Integer(), nullable=True),
    sa.Column('votes_abstain', sa.Integer(), nullable=True),
    sa.Column('votes_absent', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_resolutions_id'), 'resolutions', ['id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'OVERDUE', name='actionitemstatus'), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_table('resolution_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resolution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.Enum('AYE', 'NAY', 'ABSTAIN', 'ABSENT', name='votetype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolution_id'], ['resolutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_votes_id'), 'resolution_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_votes_id'), table_name='resolution_votes')
    op.drop_table('resolution_votes')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_resolutions_id'), table_name='resolutions')
    op.drop_table('resolutions')
    op.drop_index(op.f('ix_meeting_documents_id'), table_name='meeting_documents')
    op.drop_table('meeting_documents')
    op.drop_index(op.f('ix_meeting_attendees_id'), table_name='meeting_attendees')
    op.drop_table('meeting_attendees')
    op.drop_index(op.f('ix_agenda_items_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_committee_members_id'), table_name='committee_members')
    op.drop_table('committee_members')
    op.drop_index(op.f('ix_officer_roles_id'), table_name='officer_roles')
    op.drop_table('officer_roles')
    op.drop_index(op.f('ix_compliance_history_id'), table_name='compliance_history')
    op.drop_table('compliance_history')
    op.drop_index(op.f('ix_committees_id'), table_name='committees')
    op.drop_table('committees')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_compliance_items_id'), table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index(op.f('ix_board_members_id'), table_name='board_members')
    op.drop_table('board_members')
    # ### end Alembic commands ###
