"""Add meeting, board, resolution, compliance, and notification models

Revision ID: 6ce4767d2f5d
Revises: f71b183cb6a6
Create Date: 2025-11-06 23:02:52.920238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce4767d2f5d'
down_revision = 'f71b183cb6a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['document_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_categories_id'), 'document_categories', ['id'], unique=False)
    op.create_table('document_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_document_tags_id'), 'document_tags', ['id'], unique=False)
    op.create_table('document_tags_association',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['document_tags.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_id'), 'document_versions', ['id'], unique=False)
    op.add_column('documents', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('version_number', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_latest_version', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('parent_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'documents', ['parent_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'parent_document_id')
    op.drop_column('documents', 'is_latest_version')
    op.drop_column('documents', 'version_number')
    op.drop_column('documents', 'is_processed')
    op.drop_column('documents', 'category_id')
    op.drop_index(op.f('ix_document_versions_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('document_tags_association')
    op.drop_index(op.f('ix_document_tags_id'), table_name='document_tags')
    op.drop_table('document_tags')
    op.drop_index(op.f('ix_document_categories_id'), table_name='document_categories')
    op.drop_table('document_categories')
    # ### end Alembic commands ###
